// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArg6CvhMTKrvAcW7JZ0kfHA-f45qR7YQA',
    appId: '1:25785657749:web:07fc4db2742efeb2932e9c',
    messagingSenderId: '25785657749',
    projectId: 'pro-bono-e5d5f',
    authDomain: 'pro-bono-e5d5f.firebaseapp.com',
    storageBucket: 'pro-bono-e5d5f.appspot.com',
    measurementId: 'G-Y8VHKZ74ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndybTXzh5xL0DgPzjSfLPz9MneSMnOd0',
    appId: '1:25785657749:android:52d27e43f2143f87932e9c',
    messagingSenderId: '25785657749',
    projectId: 'pro-bono-e5d5f',
    storageBucket: 'pro-bono-e5d5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWa76OCCH8bKhSnx11ejWCRPNmjCRHFZM',
    appId: '1:25785657749:ios:06e3f224bf2d886e932e9c',
    messagingSenderId: '25785657749',
    projectId: 'pro-bono-e5d5f',
    storageBucket: 'pro-bono-e5d5f.appspot.com',
    iosClientId: '25785657749-qefqlo08u0mcaik3hboa53d4iik9o6i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.spd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWa76OCCH8bKhSnx11ejWCRPNmjCRHFZM',
    appId: '1:25785657749:ios:06e3f224bf2d886e932e9c',
    messagingSenderId: '25785657749',
    projectId: 'pro-bono-e5d5f',
    storageBucket: 'pro-bono-e5d5f.appspot.com',
    iosClientId: '25785657749-qefqlo08u0mcaik3hboa53d4iik9o6i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.spd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArg6CvhMTKrvAcW7JZ0kfHA-f45qR7YQA',
    appId: '1:25785657749:web:07fc4db2742efeb2932e9c',
    messagingSenderId: '25785657749',
    projectId: 'pro-bono-e5d5f',
    authDomain: 'pro-bono-e5d5f.firebaseapp.com',
    storageBucket: 'pro-bono-e5d5f.appspot.com',
    measurementId: 'G-Y8VHKZ74ZE',
  );

}